### ISSUE TITLE
Bayesian Network Predictor

### ISSUE THREAD

**Issue by eteuler** [paulgovan/BayesianNetwork#5]
How does R shiny know what its predicting in an R Shiny bayesian network app? Is this defined in the code somewhere?

**Comment by paulgovan** [comment]
I'm not sure I understand your question but you can see the app's code in: 

Inst/bn/

The two primary scripts are server.r and ui.r

**Comment by paulgovan** [comment]
Closing since I haven't heard anything in over a week.
