### ISSUE TITLE
The csv format

### ISSUE THREAD

**Issue by hazelnutsgz** [paulgovan/BayesianNetwork#9]
I want to know the exact format of the uploaded csv file to build network, can you offer us some examples?

**Comment by paulgovan** [comment]
Sure there's an example in the tests folder:

[https://github.com/paulgovan/BayesianNetwork/blob/master/inst/bn/tests/learning_test.csv](https://github.com/paulgovan/BayesianNetwork/blob/master/inst/bn/tests/learning_test.csv)
